config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :users, except: %i[ new ]
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'about', to: 'pages#about'
  
  root 'pages#home'

  resources :categories, except: [ :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minmum: 10, maximum: 300 }
  
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  include Gravtastic
  gravtastic

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[ show index ]
  before_action :require_same_user, only: %i[ edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = 'You can only edit or delete your own article'
        redirect_to @article
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [ :index, :show ]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to @category
    else
     render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to user_path(current_user) if logged_in? 
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase) 
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: %i[ edit update ]
  before_action :require_same_user, only: %i[ edit update ]

  def new
    @user = User.new
  end

  def edit; end

  def show
    @articles = @user.articles
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html do
          redirect_to user_path(@user),
                      notice: "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:notice] = 'You are not permitted to edit other accounts'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Author:</strong>
    <%= article.user.username %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_article_row_item.html.erb
<tr>
  <td><%= article.title %></td>
  <td><%= article.description %></td>
  <td><%= article.user.username %></td>
  <td class="text-center"><%= link_to "Show", article, class: 'btn btn-primary' %></td>
  <% if logged_in? &&  (current_user == article.user || current_user.admin? ) %>
  <td class="text-center"><%= link_to "Edit", edit_article_path(article), class: 'btn btn-secondary' %></td>
  <td class="text-center"><%= button_to "Delete", article_path(article), method: :delete, class: 'btn btn-danger'%></td>
  <% end %>
</tr>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :description, style: "display: block", class: '' %>
    <%= form.text_area :description, placeholder: 'body goes here!', class:'form-control' %>
  </div>
  <br>
  <div>
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article, class: 'btn btn-primary' %> 
  <%= link_to "Back to articles", articles_path, class: 'btn btn-secondary' %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Articles</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Body</th>
      <th scope="col">Author</th>
      <th scope="col" colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody id="articles">
    <%= will_paginate @articles, class:'pagination' %>
    <% @articles.each do |article| %>
      <%= render partial: 'articles/article_row_item', locals: { article: article } %>
    <% end %>
  </tbody>
</table>
<%= link_to "New article", new_article_path, class:'btn btn-success' %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path, class: 'btn btn-secondary' %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @article %>
<div>
  <% if logged_in? && (current_user == @article.user || current_user.admin? )%>
    <%= link_to "Edit this article", edit_article_path(@article), class: 'btn btn-secondary' %>
  <% end %>
  <%= link_to "Back to articles", articles_path, class: 'btn btn-primary' %>
  <br />
  <br>
  <% if logged_in? &&  (current_user == @article.user || current_user.admin? ) %>
    <%= button_to "Destroy this article", @article, method: :delete, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Category</th>
    </tr>
  </thead>
  <tbody id="categories">
    <%= will_paginate @categories, class:'pagination' %>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
      </tr>
      <% end %>

  </tbody>
</table>

app/views/categories/new.html.erb
<h1>Create a new Category</h1>

<%= form_with(model: @category) do |form| %>
  <% if @category&.errors&.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.label :name, "Category name", style: "display: block" %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter a category name' %>
  </div>
  <br>
  <div>
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'ALPHA BLOG', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% unless logged_in? %>
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="nav-item">
              <%= link_to 'Show All', articles_path, class: 'dropdown-item' %>
            </li>
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to 'Create', new_article_path, class: 'dropdown-item' %>
              </li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
              <li class="nav-item">
                <%= link_to current_user.username, user_path(current_user), class: 'dropdown-item' %>
              </li>
              <li class="nav-item">
                <%= button_to 'Logout', logout_path, method: :delete, class: 'dropdown-item' %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class="nav-item">
                <%= button_to 'Delete', user_path(current_user), method: :delete, class: 'dropdown-item text-danger', data: { confirm: "Are you sure?" } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
              <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: 'dropdown-item' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <%= render partial: 'layouts/header' %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "image_6483441-3.JPG", class: "d-block w-100 h-40", alt: "Great Wall of China", style: "max-height: 600px;" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "image_6483441-4.JPG", class: "d-block w-100 h-40", alt: "Cycling", style: "max-height: 600px;"  %>
    </div>
    <div class="carousel-item">
      <%= image_tag "image_6483441-5.JPG", class: "d-block w-100 h-40", alt: "Great Wall of China", style: "max-height: 600px;"  %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/home.html.erb
<!-- Jumbotron -->
<div class="p-4 shadow-4 rounded-3" style="background-color: hsl(0, 0%, 94%);">
  <h2>Home</h2>
  <p>
    Welcome to my Ruby on Rails blog! I created this site as part of my learning journey with The Pesto Group. As a new member of the team, I was eager to dive into the world of Rails and gain a deeper understanding of its fundamental concepts. This blog allowed me to explore topics like CRUD operations, user authentication with Devise, and more.
  </p>

  <hr class="my-4" />

  <p>
    From tutorials and code snippets to musings on software development, this blog has a little bit of everything. Whether you're here to learn something new or just enjoy some quality writing about Rails and web development, I invite you to take a look around and see what catches your eye. Thank you for stopping by!
  </p>
  <%= link_to 'About',  about_path, class: 'btn btn-primary'  %>
</div>
<!-- Jumbotron -->

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, class: 'form-control', placeholder: 'Enter a username' %>
  </div>
  <br>
  <div>
    <%= form.label :email, style: "display: block", class: '' %>
    <%= form.email_field :email, placeholder: 'Enter your email address', class:'form-control' %>
  </div>
  <br>
  <div>
    <%= form.label :password, style: "display: block", class: '' %>
    <%= form.password_field :password, placeholder: 'Choose a password', class:'form-control' %>
  </div>
  <br>
  <div>
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/users/_user_row_item.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <td><%= user.articles.count %></td>
  <td class="text-center"><%= link_to "Show", user, class: 'btn btn-primary' %></td>
  <% if logged_in? && (current_user == user || current_user.admin) %>
    <td class="text-center"><%= link_to "Edit", edit_user_path(user), class: 'btn btn-secondary' %></td>
    <td class="text-center"><%= button_to "Delete", user_path(user), method: :delete, class: 'btn btn-danger'%></td>
  <% end %>
</tr>

app/views/users/edit.html.erb
<% if logged_in? && current_user == @user %>
  <h1>Edit your profile</h1>
  <%= render "form", user: @user %>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Bloggers</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Articles</th>
      <th scope="col" colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody id="users">
    <%= will_paginate @users, class:'pagination' %>
    <% @users.each do |user| %>
      <%= render partial: 'users/user_row_item', locals: { user: user } %>
    <% end %>
  </tbody>
</table>
<%= link_to "New article", new_article_path, class:'btn btn-success' %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>
<%= image_tag @user.gravatar_url, class: "gravatar shadow" %>
<% if @articles.count > 0 %>
<h3>Articles</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Body</th>
      <th scope="col">Author</th>
      <th scope="col" colspan="3" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody id="articles">
    <% @articles.each do |article| %>
      <%= render partial: 'articles/article_row_item', locals: { article: article } %>
    <% end %>
  </tbody>
</table>
<% end %>